site_name: Schedula

theme:
  name: material

nav:
  - Home: "index.md"
  - "Lean Inception":
      - "Foo": "Lean Inception/Foo.md"
  - "Modelagem Agil":
      - "Epicos, Features, e Historias de Usuários": "Modelagem Agil/NiveisDeAbstracao.md"
      - "Priorização": "Modelagam Agil/Priorizacao.md"
      - Backlog: "Modelagem Agil/Backlog.md"
  - "Gestão de Projeto":
      - "Plano de Gestão de Riscos": "Gestao/PlanoDeGestaoDeRiscos.md"
      - "Plano de Custos": "Gestao/PlanoDeCustos.md"
  - Sobre: "about.md"
  - Reuniões:
      - Dailies: "Reunioes/Dailies.md"
      - Dinâmicas: "Reunioes/Dinamicas.md"
      - Planning: "Reunioes/Planning.md"
      - Treinamentos: "Reunioes/Treinamentos.md"
  - "Como contribuir": "politicas-de-contribuicao.md"

extra_css:
  - "styles/header.css"
  - "styles/table.css"
  - "styles/custom.css"
