site_name: Projeto agenda

theme:
  name: material

nav:
  - Home: 'index.md'
  - "Lean Inception":
    - 'Foo': 'Lean Inception/Foo.md'
  - Backlog: 'Backlog.md'
  - Sobre: 'about.md'
  - Reuniões:
    - Dailies: "Reunioes/Dailies.md"
    - Dinâmicas: "Reunioes/Dinamicas.md"
    - Treinamentos: "Reunioes/Treinamentos.md"


extra_css:
  - "styles/header.css"
  - "styles/table.css"
