site_name: Projeto agenda

theme:
  name: material

nav:
  - Home: 'index.md'
  - "Lean Inception":
    - 'Foo': 'Lean Inception/Foo.md'
  - "Modelagem Agil":
    - "Epicos, Features, e Historias de Usuários": "Modelagem Agil/NiveisDeAbstracao.md"
    - "Priorização": "Modelagam Agil/Priorizacao.md"
    - Backlog: 'Modelagem Agil/Backlog.md'
  - Sobre: 'about.md'
  - Reuniões:
    - Dailies: "Reunioes/Dailies.md"
    - Dinâmicas: "Reunioes/Dinamicas.md"
    - Treinamentos: "Reunioes/Treinamentos.md"


extra_css:
  - "styles/header.css"
  - "styles/table.css"
  - "styles/custom.css"
